/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';
import '@pro-webcomponents/core';

import {
  EventEmitter,
} from '@stencil/core';

declare global {

  namespace StencilComponents {
    interface DeathPage {

    }
  }

  interface HTMLDeathPageElement extends StencilComponents.DeathPage, HTMLStencilElement {}

  var HTMLDeathPageElement: {
    prototype: HTMLDeathPageElement;
    new (): HTMLDeathPageElement;
  };
  interface HTMLElementTagNameMap {
    'death-page': HTMLDeathPageElement;
  }
  interface ElementTagNameMap {
    'death-page': HTMLDeathPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'death-page': JSXElements.DeathPageAttributes;
    }
  }
  namespace JSXElements {
    export interface DeathPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface LandingPage {

    }
  }

  interface HTMLLandingPageElement extends StencilComponents.LandingPage, HTMLStencilElement {}

  var HTMLLandingPageElement: {
    prototype: HTMLLandingPageElement;
    new (): HTMLLandingPageElement;
  };
  interface HTMLElementTagNameMap {
    'landing-page': HTMLLandingPageElement;
  }
  interface ElementTagNameMap {
    'landing-page': HTMLLandingPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'landing-page': JSXElements.LandingPageAttributes;
    }
  }
  namespace JSXElements {
    export interface LandingPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface LazyImg {
      'alt': string;
      'src': string;
      'width': number;
    }
  }

  interface HTMLLazyImgElement extends StencilComponents.LazyImg, HTMLStencilElement {}

  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lazy-img': JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      'alt'?: string;
      'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
      'src'?: string;
      'width'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface LoginPage {

    }
  }

  interface HTMLLoginPageElement extends StencilComponents.LoginPage, HTMLStencilElement {}

  var HTMLLoginPageElement: {
    prototype: HTMLLoginPageElement;
    new (): HTMLLoginPageElement;
  };
  interface HTMLElementTagNameMap {
    'login-page': HTMLLoginPageElement;
  }
  interface ElementTagNameMap {
    'login-page': HTMLLoginPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'login-page': JSXElements.LoginPageAttributes;
    }
  }
  namespace JSXElements {
    export interface LoginPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MapPage {

    }
  }

  interface HTMLMapPageElement extends StencilComponents.MapPage, HTMLStencilElement {}

  var HTMLMapPageElement: {
    prototype: HTMLMapPageElement;
    new (): HTMLMapPageElement;
  };
  interface HTMLElementTagNameMap {
    'map-page': HTMLMapPageElement;
  }
  interface ElementTagNameMap {
    'map-page': HTMLMapPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'map-page': JSXElements.MapPageAttributes;
    }
  }
  namespace JSXElements {
    export interface MapPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyApp {

    }
  }

  interface HTMLMyAppElement extends StencilComponents.MyApp, HTMLStencilElement {}

  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProfilePage {
      'name': string;
    }
  }

  interface HTMLProfilePageElement extends StencilComponents.ProfilePage, HTMLStencilElement {}

  var HTMLProfilePageElement: {
    prototype: HTMLProfilePageElement;
    new (): HTMLProfilePageElement;
  };
  interface HTMLElementTagNameMap {
    'profile-page': HTMLProfilePageElement;
  }
  interface ElementTagNameMap {
    'profile-page': HTMLProfilePageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'profile-page': JSXElements.ProfilePageAttributes;
    }
  }
  namespace JSXElements {
    export interface ProfilePageAttributes extends HTMLAttributes {
      'name'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
