/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@ionic/core';
import 'ionicons';
import '@pro-webcomponents/core';


declare global {

  namespace StencilComponents {
    interface DeathPage {

    }
  }

  interface HTMLDeathPageElement extends StencilComponents.DeathPage, HTMLStencilElement {}

  var HTMLDeathPageElement: {
    prototype: HTMLDeathPageElement;
    new (): HTMLDeathPageElement;
  };
  interface HTMLElementTagNameMap {
    'death-page': HTMLDeathPageElement;
  }
  interface ElementTagNameMap {
    'death-page': HTMLDeathPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'death-page': JSXElements.DeathPageAttributes;
    }
  }
  namespace JSXElements {
    export interface DeathPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface LandingPage {

    }
  }

  interface HTMLLandingPageElement extends StencilComponents.LandingPage, HTMLStencilElement {}

  var HTMLLandingPageElement: {
    prototype: HTMLLandingPageElement;
    new (): HTMLLandingPageElement;
  };
  interface HTMLElementTagNameMap {
    'landing-page': HTMLLandingPageElement;
  }
  interface ElementTagNameMap {
    'landing-page': HTMLLandingPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'landing-page': JSXElements.LandingPageAttributes;
    }
  }
  namespace JSXElements {
    export interface LandingPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MapPage {

    }
  }

  interface HTMLMapPageElement extends StencilComponents.MapPage, HTMLStencilElement {}

  var HTMLMapPageElement: {
    prototype: HTMLMapPageElement;
    new (): HTMLMapPageElement;
  };
  interface HTMLElementTagNameMap {
    'map-page': HTMLMapPageElement;
  }
  interface ElementTagNameMap {
    'map-page': HTMLMapPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'map-page': JSXElements.MapPageAttributes;
    }
  }
  namespace JSXElements {
    export interface MapPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyApp {

    }
  }

  interface HTMLMyAppElement extends StencilComponents.MyApp, HTMLStencilElement {}

  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface SettingsPage {

    }
  }

  interface HTMLSettingsPageElement extends StencilComponents.SettingsPage, HTMLStencilElement {}

  var HTMLSettingsPageElement: {
    prototype: HTMLSettingsPageElement;
    new (): HTMLSettingsPageElement;
  };
  interface HTMLElementTagNameMap {
    'settings-page': HTMLSettingsPageElement;
  }
  interface ElementTagNameMap {
    'settings-page': HTMLSettingsPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'settings-page': JSXElements.SettingsPageAttributes;
    }
  }
  namespace JSXElements {
    export interface SettingsPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface WhoarePage {

    }
  }

  interface HTMLWhoarePageElement extends StencilComponents.WhoarePage, HTMLStencilElement {}

  var HTMLWhoarePageElement: {
    prototype: HTMLWhoarePageElement;
    new (): HTMLWhoarePageElement;
  };
  interface HTMLElementTagNameMap {
    'whoare-page': HTMLWhoarePageElement;
  }
  interface ElementTagNameMap {
    'whoare-page': HTMLWhoarePageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'whoare-page': JSXElements.WhoarePageAttributes;
    }
  }
  namespace JSXElements {
    export interface WhoarePageAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
